### ISSUE TITLE
Add `gix diff` to CLI

### ISSUE THREAD

**Issue by cruessler** [GitoxideLabs/gitoxide#1625]
### Summary 💡

I found that there is no `gix diff` yet, but I think it would be very useful in the context of developing `gix blame`. I searched the issue list, but as far as I could tell, there was no issue related to `gix diff` yet. I’d like to start working on adding `gix diff` if it isn’t on anyone’s todo list yet.

### Motivation 🔦

This will be helpful in debugging, in particular for `gix blame`.

### Tasks

- [x] `gix diff tree` #1626

**Comment by cruessler** [comment]
Are there any other subcommands it would make sense to implement at this point? I still have context, but for `gix blame` I currently don’t need more as far as I can tell.

**Comment by Byron** [comment]
If it's good enough for you let's close it, I also have no plans for more right now.
