### ISSUE TITLE
New `pure-rust-build` failure - seems transient

### ISSUE THREAD

**Issue by EliahKagan** [GitoxideLabs/gitoxide#1636]
### Current behavior 😯

The `pure-rust-build` job has failed on CI in the merge of #1635. But this seems unrelated to any changes in #1635. It looks like it is instead to a transient problem connecting and downloading data from one of Debian's repositories. [The run log has](https://github.com/GitoxideLabs/gitoxide/actions/runs/11415485447/job/31765585229#step:4:16):

```text
W: Failed to fetch http://deb.debian.org/debian-security/dists/buster/updates/InRelease  Connection failed [IP: 146.75.94.132 80]
```

### Expected behavior 🤔

When I fast-forwarded the main branch of my fork, the same CI check passed, and [its run log has](https://github.com/EliahKagan/gitoxide/actions/runs/11415509823/job/31765640498#step:4:9):

```text
Get:2 http://deb.debian.org/debian-security buster/updates InRelease [34.8 kB]
```

I recommend rerunning the job. My guess is that it will pass if that is done (and this can be closed).

### Git behavior

Not applicable.

### Steps to reproduce 🕹

See links above.

**Comment by Byron** [comment]
I think so, too. It was no rerun and I'd think it will pass.

**Comment by EliahKagan** [comment]
Yes, [it is working now](https://github.com/GitoxideLabs/gitoxide/actions/runs/11415485447/job/31765866267). Thanks!
