### ISSUE TITLE
`max-pure` feature is not pure (pulls in `libsqlite3-sys`)

### ISSUE THREAD

**Issue by tanriol** [GitoxideLabs/gitoxide#1681]
### Current behavior 😯

```
$ cargo build --target aarch64-unknown-linux-musl --release --no-default-features --features=max-pure
[...]
error: failed to run custom build command for `libsqlite3-sys v0.30.1`
```

### Expected behavior 🤔

`max-pure` feature should be actually pure (ideally, CI should ensure it works without a C compiler available at all)

**Comment by Byron** [comment]
Thanks for bringing this to my attention.

It's true that `max-pure` is over-promising at the moment and what really is tested on CI is that a build is possible without additional tooling, like `cmake`. Here is the listing of prerequisites that are currently required to make any Rust build:

https://github.com/GitoxideLabs/gitoxide/blob/2fc93f76798ce35f038d52a85b1841fff5280837/.github/workflows/ci.yml#L33-L41

Note that `curl` is used to install Rust via `rustup.rs`.

As of now, it's not possible to make any Rust build without a C compiler as it invokes the linker through it. Thanks to that, C-dependencies can always sneak in and build as long as they don't invoke more than `make` to compile.

Even though this particular issue can be solved by turning off `gitoxide-core-tools-query` for the `max-pure` build, it seems that what this issue really is about is to be able to build without a functional `gcc`.

Maybe the CI run could be tuned to replace `gcc` with a wrapper that only allows linking - then an attempt to build an actual C file would fail naturally, and one would maybe notice even more such invocations.
Maybe there is also a way to force Rust to use `ld` directly?

**Comment by NobodyXu** [comment]
There's nightly flag for using rustup distributed lld, honestly I wish something like zig-cc is provided via rustup.

**Comment by Byron** [comment]
That should be possible to integrate on CI and would solve the problem. Thanks for suggesting!

**Comment by Byron** [comment]
Thanks a lot for your help!

I have set this issue to `blocked` once again as `ring` currently builds some C code as part of its own compilation. It probably does so for very good reason, but while it's doing so a truly pure Rust build can't be accomplished unless one turns off HTTPS transport.

I could also imagine an intermediate step which involves setting up a `pure` target, one that tries to achieve a pure Rust build without having to provide `max` features.

**Comment by tanriol** [comment]
Not that I personally needed it to be absolutely pure Rust - removing `gitoxide-core-tools-query` and `gitoxide-core-tools-corpus` from `max-pure` was enough for my case to work, everything else cross-compiled successfully - but that's what the feature naming implied.

**Comment by Byron** [comment]
Great to hear. Then I'd say I keep the `pure` and `max-pure` situation in mind and we call this issue resolved once `max-pure` doesn't pull in `sqlite` anymore.
