### ISSUE TITLE
Kanban board is private, readme suggests it should be public

### ISSUE THREAD

**Issue by EliahKagan** [GitoxideLabs/gitoxide#1714]
### Current behavior 😯

The [Kanban board](https://github.com/orgs/GitoxideLabs/projects/1/views/1) is private. On the [Projects tab](https://github.com/GitoxideLabs/gitoxide/projects?query=is%3Aopen):

![screenshot of the portion of the Projects tab that shows the Kanban board project and its private visibility](https://github.com/user-attachments/assets/a15d6e6e-958c-440e-89bb-d6a11f59f94c)

I'm able to access it, because I'm a member of the GitoxideLabs organization, but it is not visible to most people (or if one is logged out).

Maybe this happened when the repository was moved into the GitoxideLabs organization?

### Expected behavior 🤔

I believe it is intended to be public, because:

1. I don't know of any reason for it to be private.
2. The projects associated with this repository were public in the past.
3. The README refers to it in a way makes the most sense if people who have not yet begin to contribute to gitoxide can read it.

On that third point, this is [the relevant part](https://github.com/GitoxideLabs/gitoxide?tab=readme-ov-file#contributions) of the readme:

> A backlog for work ready to be picked up is [available in the Project's Kanban board](https://github.com/GitoxideLabs/gitoxide/projects), which contains instructions on how to pick a task. If it's empty or you have other questions, feel free to [start a discussion](https://github.com/GitoxideLabs/gitoxide/discussions) or reach out to @&NoBreak;Byron [privately](https://keybase.io/byronbates).

If for some reason the Kanban board is to be kept private, then the readme could be edited.

Although it looks like GitHub would let me close the Kanban board project, it doesn't seem like it would let me make it public. I think [the information here](https://docs.github.com/en/issues/planning-and-tracking-with-projects/managing-your-project/managing-access-to-your-projects) may help in making it public. Maybe it became private unintentionally when moving this repository into the GitoxideLabs organization, relating to the organization's base permission for projects, as described in [the note here](https://docs.github.com/en/organizations/managing-organization-settings/managing-base-permissions-for-projects#about-base-permissions-for-projects).

### Git behavior

Not applicable.

### Steps to reproduce 🕹

Examining the project identifies it as private and shows a lock icon, as shown in the screenshot above, and attempting view it while logged out verified that this is currently the case.

**Comment by Byron** [comment]
Thanks for making me aware, this was an oversight. These are now private by default it seems.
This has now been corrected.

**Comment by EliahKagan** [comment]
Thanks!
