### ISSUE TITLE
Consider running fuzz and stress tests against main in a cron workflow

### ISSUE THREAD

**Issue by caspervonb** [GitoxideLabs/gitoxide#226]
CI takes quite a while longer than it needs to, maybe fuzz and stress tests could be run against main on a cron job instead.
Advantage would be that we can fuzz and stress test for hours as it's not in the main CI test pipeline but an auxiliary one.

**Comment by Byron** [comment]
Configuration change were made to make this happen. A 1pm the first stress test should run, then again 12 hours later.

**Comment by Byron** [comment]
Miscommunication, working on it. Thanks for the manual trigger, if it runs through I will be closing this one.
